const translations = {
  de: { navCatalog:'Katalog', navExams:'Prüfungen', navDelivery:'Lieferung', navAccount:'Mein Konto', cart:'Warenkorb', eyebrow:'Originale Prüfungstrainings', headlineA:'Deutsch lernen?', headlineB:'Wir helfen dir dabei.', subA:'Von der ersten Lektion bis zum', subB:'Prüfungserfolg', cta:'Passende Bücher entdecken', help:'Beratung erhalten', stamp:'ERFOLG BEGINNT\nMIT DER RICHTIGEN\nVORBEREITUNG', trust1:'100% Original\nGeprüfte Bücher', trust2:'Support\nWir helfen dir', trust3:'Sicher bezahlen\nEinfach & geschützt', trust4:'+2000\nZufriedene Kunden', whyEyebrow:'Warum PrüfungStore?', whyTitle:'Alles, was du für deine Prüfung brauchst.', whyText:'Strukturierte Vorbereitung, echte Modelltests und Unterstützung auf deinem Weg zum Zertifikat.', f1Title:'Originale Bücher', f1Text:'Aktuelle Materialien für TELC, Goethe und ÖSD.', f2Title:'Realistische Tests', f2Text:'Übe mit Modelltests, die dem echten Format folgen.', f3Title:'Schritt für Schritt', f3Text:'Klarer Lernplan von A1 bis C1.', f4Title:'Dein Erfolg', f4Text:'Bereite dich sicher vor und bestehe deine Prüfung.', catalogEyebrow:'Prüfungsvorbereitung', catalogTitle:'Finde dein passendes Buch.', productText:'TELC, Goethe und ÖSD Modelltests mit Lösungen.', add:'In den Warenkorb', footer:'Dein Partner für deutsche Sprachprüfungen.', modalTitle:'Deine Bestellung', name:'Name', phone:'Telefonnummer', submit:'Bestellung bestätigen'},
  ar: { navCatalog:'الكتالوج', navExams:'الامتحانات', navDelivery:'التوصيل', navAccount:'حسابي', cart:'السلة', eyebrow:'كتب تحضير أصلية للامتحانات', headlineA:'تعلّم الألمانية؟', headlineB:'نحن نساعدك في ذلك.', subA:'من أول درس إلى', subB:'نجاحك في الامتحان', cta:'اكتشف الكتب المناسبة', help:'احصل على استشارة', stamp:'النجاح يبدأ\nبالتحضير\nالصحيح', trust1:'أصلي 100٪\nكتب موثوقة', trust2:'دعم\nنحن هنا لمساعدتك', trust3:'دفع آمن\nبسهولة وحماية', trust4:'+2000\nعميل راضٍ', whyEyebrow:'لماذا PrüfungStore؟', whyTitle:'كل ما تحتاجه لامتحانك.', whyText:'تحضير منظم، نماذج امتحانات حقيقية ودعم مستمر حتى تحصل على الشهادة.', f1Title:'كتب أصلية', f1Text:'مواد حديثة لامتحانات TELC وGoethe وÖSD.', f2Title:'نماذج واقعية', f2Text:'تدرّب على نماذج تحاكي الامتحان الحقيقي.', f3Title:'خطوة بخطوة', f3Text:'خطة تعلم واضحة من A1 إلى C1.', f4Title:'نجاحك', f4Text:'استعد بثقة واجتز امتحانك.', catalogEyebrow:'التحضير للامتحان', catalogTitle:'اعثر على كتابك المناسب.', productText:'نماذج TELC وGoethe وÖSD مع الحلول.', add:'أضف إلى السلة', footer:'شريكك لامتحانات اللغة الألمانية.', modalTitle:'طلبك', name:'الاسم', phone:'رقم الهاتف', submit:'تأكيد الطلب'},
  nl: { navCatalog:'Catalogus', navExams:'Examens', navDelivery:'Levering', navAccount:'Mijn account', cart:'Winkelmand', eyebrow:'Originele examentrainingen', headlineA:'Duits leren?', headlineB:'Wij helpen je daarbij.', subA:'Van je eerste les tot', subB:'succes voor je examen', cta:'Ontdek passende boeken', help:'Vraag advies', stamp:'SUCCES BEGINT\nMET DE JUISTE\nVOORBEREIDING', trust1:'100% Origineel\nGecontroleerde boeken', trust2:'Support\nWij helpen je', trust3:'Veilig betalen\nEenvoudig en beschermd', trust4:'+2000\nTevreden klanten', whyEyebrow:'Waarom PrüfungStore?', whyTitle:'Alles voor jouw examen.', whyText:'Een duidelijke voorbereiding, echte oefentoetsen en hulp op weg naar je certificaat.', f1Title:'Originele boeken', f1Text:'Actueel materiaal voor TELC, Goethe en ÖSD.', f2Title:'Realistische toetsen', f2Text:'Oefen met modellen die het echte examen volgen.', f3Title:'Stap voor stap', f3Text:'Een duidelijk leerplan van A1 tot C1.', f4Title:'Jouw succes', f4Text:'Bereid je goed voor en slaag voor je examen.', catalogEyebrow:'Examenvoorbereiding', catalogTitle:'Vind jouw boek.', productText:'TELC-, Goethe- en ÖSD-modellen met antwoorden.', add:'In winkelmand', footer:'Jouw partner voor Duitse taalexamens.', modalTitle:'Je bestelling', name:'Naam', phone:'Telefoonnummer', submit:'Bestelling bevestigen'}
};

let cart = [];
let selectedProduct = '';
const $ = (id) => document.getElementById(id);
function showToast(message) { const toast = $('toast'); toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 3200); }
function setLanguage(language) { const t = translations[language] || translations.de; document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'; document.querySelectorAll('[data-i18n]').forEach((el) => { const value = t[el.dataset.i18n]; if (value) el.textContent = value; }); localStorage.setItem('pruefung_language', language); }
function updateCart() { $('cartCount').textContent = String(cart.length); }
function openModal(product = '') { selectedProduct = product; $('modalSummary').textContent = product ? `${product} — ${translations[$('language').value].add}` : ''; $('modalError').classList.remove('show'); $('modalBackdrop').classList.add('open'); $('customerName').focus(); }
function closeModal() { $('modalBackdrop').classList.remove('open'); }
function submitOrder() { const name = $('customerName').value.trim(); const phone = $('customerPhone').value.trim(); const error = $('modalError'); if (name.length < 2) { error.textContent = 'Bitte gib deinen Namen ein.'; error.classList.add('show'); $('customerName').focus(); return; } if (!/^[+\d][\d\s()-]{7,}$/.test(phone)) { error.textContent = 'Bitte gib eine gültige Telefonnummer ein.'; error.classList.add('show'); $('customerPhone').focus(); return; } cart.push(selectedProduct || 'Beratung'); updateCart(); closeModal(); showToast('Danke! Wir melden uns schnell bei dir.'); }
document.addEventListener('DOMContentLoaded', () => { const saved = localStorage.getItem('pruefung_language'); $('language').value = saved && translations[saved] ? saved : 'de'; setLanguage($('language').value); $('language').addEventListener('change', (event) => setLanguage(event.target.value)); document.querySelectorAll('.addButton').forEach((button) => button.addEventListener('click', () => openModal(button.dataset.product))); $('cartButton').addEventListener('click', () => openModal(cart[0] || '')); $('helpButton').addEventListener('click', () => openModal('Beratung')); $('closeModal').addEventListener('click', closeModal); $('modalBackdrop').addEventListener('click', (event) => { if (event.target === $('modalBackdrop')) closeModal(); }); $('submitOrder').addEventListener('click', submitOrder); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeModal(); }); updateCart(); });
window.addEventListener('error', () => showToast('Etwas ist schiefgelaufen. Bitte versuche es erneut.'));
